/* tslint:disable */
/* eslint-disable */
/**
 * PAY.JP Token API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// import { exists, mapValues } from '../runtime';

function exists(json: any, key: string) {
    const value = json[key];
    return value !== null && value !== undefined;
}

function mapValues(data: any, fn: (item: any) => any) {
    return Object.keys(data).reduce((acc, key) => ({ ...acc, [key]: fn(data[key]) }), {});
}

/**
 *
 * @export
 * @interface TokenForm
 */
export interface TokenForm {
    /**
     *
     * @type {string}
     * @memberof TokenForm
     */
    cardNumber: string;
    /**
     *
     * @type {string}
     * @memberof TokenForm
     */
    cardExpMonth: string;
    /**
     *
     * @type {string}
     * @memberof TokenForm
     */
    cardExpYear: string;
    /**
     *
     * @type {string}
     * @memberof TokenForm
     */
    cardCvc?: string;
    /**
     *
     * @type {string}
     * @memberof TokenForm
     */
    cardName?: string;
}

export function TokenFormFromJSON(json: any): TokenForm {
    return TokenFormFromJSONTyped(json, false);
}

export function TokenFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenForm {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        cardNumber: json["card[number]"],
        cardExpMonth: json["card[exp_month]"],
        cardExpYear: json["card[exp_year]"],
        cardCvc: !exists(json, "card[cvc]") ? undefined : json["card[cvc]"],
        cardName: !exists(json, "card[name]") ? undefined : json["card[name]"],
    };
}

export function TokenFormToJSON(value?: TokenForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        "card[number]": value.cardNumber,
        "card[exp_month]": value.cardExpMonth,
        "card[exp_year]": value.cardExpYear,
        "card[cvc]": value.cardCvc,
        "card[name]": value.cardName,
    };
}
