name: Check latest PAYJP.SDK

on: push
  # schedule:
  #   - cron: 0 0 * * *

jobs:
  check_latest:
    runs-on: macos-latest
    steps:
      - id: latest-ios
        uses: oprypin/find-latest-tag@v1
        with:
          repository: payjp/payjp-ios
          release-only: true
      - id: latest-android
        uses: oprypin/find-latest-tag@v1
        with:
          repository: payjp/payjp-android
          release-only: true
      - uses: actions/checkout@v2
      - name: Update with latest sdk
        run: |
          jq '. + { ios: "${{ steps.latest-ios.outputs.tag }}", android: "${{ steps.latest-android.outputs.tag }}"}' sdkconfig.json > tmp.json && mv tmp.json sdkconfig.json
      - run: git diff --exit-code
      - if: success()
        run: echo "no update"
      - name: Create PR
        if: failure()
        run: |
          sudo gem install cocoapods
          cd example && yarn --frozen-lockfile && cd ../
          cd example/ios && pod update PAYJP && cd ../../
          DATE=`date +"%Y%m%d"`
          BRANCH_NAME="auto-update$DATE"
          git config --global user.email "misc@pay.jp"
          git config --global user.name "pay kun"
          git checkout -b "$BRANCH_NAME"
          git add sdkconfig.json
          git add example/ios/Podfile.lock
          git commit -m "Bump up ios: ${{ steps.latest-ios.outputs.tag }}, android: ${{ steps.latest-android.outputs.tag }}"
          git push origin "$BRANCH_NAME"
          hub pull-request -b master -h $BRANCH_NAME -m "[Auto]Update SDK payjp-ios: ${{ steps.latest-ios.outputs.tag }}, payjp-android: ${{ steps.latest-android.outputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




